accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('profile/<int:user_pk>/post/', views.profile_post_view, name='profile_post'),
	path('profile/<int:user_pk>/about/', views.profile_about_view, name='profile_about'),
	path('profile/<int:user_pk>/photos/', views.profile_photos_view, name='profile_photos'),
	path('profile/<int:pk>/groups/', views.user_group_list, name='profile_groups'),
	path('userprofile/<int:user_pk>/update', views.update_user_profile_data_view, name='userprofile_update'),
	path('user/<int:user_pk>/update', views.update_user_data_view, name='user_update'),
	path('user/settings/', views.user_settings_view, name='user_settings'),
	path('user-profile/<int:user_pk>/update', views.update_user_profile_view, name='update_user_profile'),
	path('follow/<int:user_pk>/', views.follow_view, name='follow'),
	# path('followers-list/<int:user_pk>/', views.followers_list_view, name='followers_list'),
	path('follow-list/<int:user_pk>/<str:follow_type>/', views.follow_list_view, name='follow_list'),
	path('send-friend-request/<int:to_user_pk>/', views.send_friend_request_view, name='send_friend_request'),
	path('delete-friend-request/<int:to_user_pk>/<int:from_user_pk>/', views.delete_friend_request_view, name='delete_friend_request'),
	path('accept-friend-request/<int:from_user_pk>/', views.accept_friend_request_view, name='accept_friend_request'),
	path('friend-request-list/', views.friend_request_list_view, name='friend_request_list'),
	path('friend-list/<int:user_pk>/', views.friend_list_view, name='friend_list'),
	path('remove-friend/<int:user_pk>/', views.remove_friend_view, name='remove_friend'),
	path('user-search', views.user_search_view, name='user_search'),
]

chats/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.thread_view, name='threads'),
	path('<int:user_pk>/', views.thread_chat_view, name='thread_chat'),
	path('chat/<int:thread_pk>/create', views.chat_create_view, name='chat_create'),
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import user_signup_view
from posts.views import home_page_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', user_signup_view, name='signup'),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.account.urls')),
    path('', home_page_view, name='home'),  # root URL maps to HomePageView
    path('groups/', include('groups.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings


User = settings.AUTH_USER_MODEL

# Create your models here.


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	other_name = models.CharField(max_length=200, null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	phone = models.CharField(max_length=50, null=True, blank=True)
	occupation = models.CharField(max_length=200, null=True, blank=True)
	location = models.CharField(max_length=250, null=True, blank=True)
	overview = models.TextField(null=True, blank=True)
	marital_status = models.CharField(max_length=100, null=True, blank=True)
	followers = models.ManyToManyField(User, related_name='followed_users')
	friends = models.ManyToManyField(User, related_name='+')

	@property
	def full_name(self):
		return f'{self.user.first_name} {self.user.last_name}'

	def get_profileimage(self):
		return self.profileimage_set.all()[0].profile_image.url

	def get_coverimage(self):
		return self.coverimage_set.all()[0].cover_image.url

class FriendRequest(models.Model):
	from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created',]

	def __str__(self):
		return f'{self.from_user.username} friend request to {self.to_user.username}'

class ProfileImage(models.Model):
	userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	profile_image = models.ImageField(upload_to='profile_images/%Y-%m-%d/', default='profile_images/placeholder.jpg')
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-created',)


class CoverImage(models.Model):
	userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	cover_image = models.ImageField(upload_to='cover_images/%Y-%m-%d/', default='cover_images/placeholder.jpg')
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-created',)

accounts/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from django import forms
from .models import UserProfile, ProfileImage, CoverImage


class UserSignUpForm(SignupForm):
	first_name = forms.CharField(max_length=200)
	last_name = forms.CharField(max_length=200)

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'mt-3'
		self.helper.layout = Layout(
			Div(
				Div('first_name', css_class='col'),
				Div('last_name', css_class='col'),
				css_class='form-row',
			),
			Div('email'),
			Div('username'),
			Div('password1'),
			Div('password2'),
			Submit('submit', 'Sign up', css_class='w-100 btn btn-primary'),
		)

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ['id', 'user', 'friends', 'followers']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields.values():
			field.required = False

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'username']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields.values():
			field.required = False

class UserProfileSettingsForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['other_name', 'phone']

class UserProfileImageForm(forms.ModelForm):
	class Meta:
		model = ProfileImage
		fields = ['profile_image',]

class UserCoverImageForm(forms.ModelForm):
	class Meta:
		model = CoverImage
		fields = ['cover_image',]

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.views.generic import TemplateView, View, ListView, DetailView
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from allauth.account.views import SignupView
from allauth.account.forms import ChangePasswordForm
from django.contrib.auth.forms import PasswordChangeForm
from accounts.forms import (
	UserSignUpForm,
	UserProfileForm,
	UserForm,
	UserProfileSettingsForm,
	UserProfileImageForm,
	UserCoverImageForm
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from posts.models import Post, PostImage
from accounts.utils import get_all_photos, get_friend_request_object, get_user_post_feeds, get_all_post_photos, filter_user_queryset
from posts.decorators import AjaxRequiredOnlyMixin
from accounts.models import UserProfile, FriendRequest

# Create your views here.

class UserSignUpView(SignupView):
	form_class = UserSignUpForm

user_signup_view = UserSignUpView.as_view()

class ProfilePostView(LoginRequiredMixin, TemplateView):
	template_name = 'accounts/profile_post.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		user = get_object_or_404(User, pk=kwargs['user_pk'])
		context['posts'] = get_user_post_feeds(self.request, kwargs['user_pk'])
		context['recent_photos'] = get_all_photos(self.request, user.pk)[:6]
		context['user'] = user
		context['page'] = 'profile_post'
		context['userprofile_form'] = UserProfileForm(instance=user.userprofile)
		context['user_form'] = UserForm(instance=user)
		return context

profile_post_view = ProfilePostView.as_view()

class ProfileAboutView(LoginRequiredMixin, TemplateView):
	template_name = 'accounts/profile_about.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		user = get_object_or_404(User, pk=kwargs['user_pk'])
		context['user'] = user
		context['page'] = 'profile_about'
		context['userprofile_form'] = UserProfileForm(instance=user.userprofile)
		context['user_form'] = UserForm(instance=user)
		# print(user.userprofile._meta.get_fields())
		field_dict = {}
		icon_classes = {'marital_status': 'fa fa-heart', 'birth_date': 'fa fa-calendar', 'occupation': 'fa fa-briefcase', 'location': 'fa fa-map-marker-alt', 'date_joined': 'fa fa-calendar', 'email': 'fa fa-envelope'}
		field_notes = {'marital_status': 'Status', 'birth_date': 'Born', 'occupation': '', 'location': 'Lives in', 'date_joined': 'Joined on', 'email': 'Email'}
		for field in user.userprofile._meta.fields:
			if field.name in ('marital_status', 'birth_date', 'occupation', 'location'):
				field_dict[field.name] = {
					'icon_class': icon_classes[field.name],
					'field_note': field_notes[field.name],
					'field_value': getattr(user.userprofile, field.name),
					'model_name': 'userprofile',
				}
		for field in user._meta.fields:
			if field.name in ('date_joined', 'email',):
				field_dict[field.name] = {
					'icon_class': icon_classes[field.name],
					'field_note': field_notes[field.name],
					'field_value': getattr(user, field.name),
					'model_name': 'user',
				}
		context['field_dict'] = field_dict
		return context

profile_about_view = ProfileAboutView.as_view()

class ProfilePhotosView(LoginRequiredMixin, TemplateView):
	template_name = 'accounts/profile_photos.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		user = User.objects.get(pk=kwargs['user_pk'])
		context['user'] = user
		context['post_photos'] = get_all_post_photos(self.request, kwargs['user_pk'])
		context['page'] = 'profile_photos'
		return context

profile_photos_view = ProfilePhotosView.as_view()

class UpdateUserProfileDataView(UserPassesTestMixin, LoginRequiredMixin, View):
	def dispatch(self, request, *args, **kwargs):
		self.user = get_object_or_404(User, pk=kwargs['user_pk'])
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		form = UserProfileForm(
			request.POST,
			instance=self.user.userprofile
		)
		if form.is_valid():
			form.save()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == self.user 

update_user_profile_data_view = UpdateUserProfileDataView.as_view()

class UpdateUserDataView(UserPassesTestMixin, LoginRequiredMixin, View):
	def dispatch(self, request, *args, **kwargs):
		self.user = get_object_or_404(User, pk=kwargs['user_pk'])
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		form = UserForm(
			request.POST,
			instance=self.user,
		)
		if form.is_valid():
			form.save()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == self.user 

update_user_data_view = UpdateUserDataView.as_view()

class UserSettingsView(LoginRequiredMixin, TemplateView):
	template_name = 'accounts/settings.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['profile_form'] = UserProfileSettingsForm(instance=self.request.user.userprofile)
		context['user_form'] = UserForm(instance=self.request.user)
		context['password_form'] = PasswordChangeForm(self.request.user)
		return context

	def post(self, request, *args, **kwargs):
		data = request.POST
		user_form = UserForm(data, instance=request.user)
		profile_form = UserProfileSettingsForm(data, instance=request.user.userprofile) 
		password_form = PasswordChangeForm(request.user, data)
		if 'user-profile-form' in data:
			if user_form.is_valid() and profile_form.is_valid():
				user_form.save()
				profile_form.save()
				messages.success(request, 'Profile updated successfully')
				return redirect('user_settings')
		elif 'password-form' in data:
			if password_form.is_valid():
				user = password_form.save()
				update_session_auth_hash(request, user)
				messages.success(request, 'Your password was changed successfully')
				return redirect('user_settings')
			else:
				messages.error(request, 'An error occured from your input')
		return self.render_to_response({'user_form': user_form, 'profile_form': profile_form, 'password_form': password_form,})

user_settings_view = UserSettingsView.as_view()

class UpdateUserProfileView(UserPassesTestMixin, LoginRequiredMixin, TemplateView):
	template_name = 'accounts/profile-edit.html'

	def dispatch(self, request, *args, **kwargs):
		self.user = User.objects.get(pk=kwargs['user_pk'])
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		user_form = UserForm(request.POST, instance=self.user)
		profile_form = UserProfileForm(request.POST, instance=self.user.userprofile)
		profile_image_form = UserProfileImageForm(request.POST, request.FILES)
		cover_image_form = UserCoverImageForm(request.POST, request.FILES)

		if user_form.is_valid() and profile_form.is_valid() and profile_image_form.is_valid() and cover_image_form.is_valid():
			user_form.save()
			user_profile = profile_form.save()
			if request.FILES.get('profile_image'):
				profile_image = profile_image_form.save(commit=False)
				profile_image.userprofile = user_profile
				profile_image.save()
			if request.FILES.get('cover_image'):
				cover_image = cover_image_form.save(commit=False)
				cover_image.userprofile = user_profile
				cover_image.save()
			messages.success(request, 'Your Profile Has Been Updated Successfully')
			return redirect(request.META.get('HTTP_REFERER'))
		return self.render_to_response({
			'user_form': user_form,
			'profile_form': profile_form,
			'profile_image_form': profile_image_form,
			'cover_image_form': cover_image_form,
		})

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['user'] = self.user
		context['user_form'] = UserForm(instance=self.user)
		context['profile_form'] = UserProfileForm(instance=self.user.userprofile)
		context['profile_image_form'] = UserProfileImageForm()
		context['cover_image_form'] = UserCoverImageForm()
		return context 

	def test_func(self):
		return self.request.user == self.user

update_user_profile_view = UpdateUserProfileView.as_view()

class FollowView(AjaxRequiredOnlyMixin, View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({'status': 'not logged in'})
		userprofile = User.objects.get(pk=kwargs['user_pk']).userprofile
		user = request.user
		if user in userprofile.followers.all():
			userprofile.followers.remove(user)
			action = 'unfollow'
		else:
			userprofile.followers.add(user)
			action = 'follow'

		return JsonResponse(
			{
				'status': 'ok',
				'action': action,
				'num_of_followers': userprofile.followers.all().count(),
			}
		)

follow_view = FollowView.as_view()

class FollowListView(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		user = User.objects.get(pk=kwargs['user_pk'])
		if kwargs['follow_type'] == 'followers':
			template_name = 'accounts/user_followers_list.html'
			page = 'followers'
		elif kwargs['follow_type'] == 'following':
			template_name = 'accounts/user_following_list.html'
			page = 'following'
		context = {'user': user, 'page': page,}
		return render(request, template_name, context)

follow_list_view = FollowListView.as_view()

class SendFriendRequestView(LoginRequiredMixin, UserPassesTestMixin, View):
	def post(self, request, *args, **kwargs):
		to_user = User.objects.get(pk=kwargs['to_user_pk'])
		obj, created = FriendRequest.objects.get_or_create(
			from_user=request.user, to_user=to_user
		)
		if not created:
			messages.warning(request, 'Friend Request Already Sent')
		
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		to_user = User.objects.get(pk=self.kwargs['to_user_pk'])

accounts/templates/accounts/friend_list.html
{% extends 'base.html' %}

{% block title %}
    {% if request.user == user %}
        Your
    {% else %}
        {{ user.username | capfirst }}'s
    {% endif %}
    Friends
{% endblock title %}

{% block content %}

    <div class="container">
        {% include 'accounts/profile_start.html' %}
        <div class="row p-3">
			<!-- Friends -->

			<div class="col-12">
				<div class="card p-4 bg-white">
					<div class="d-flex flex-wrap align-items-md-center justify-content-between">
						<span class="font-weight-bold f-lg flex-shrink-0">Friends</span>
						<div class="d-flex flex-wrap align-items-start align-items-md-center">
                            {% if friends %}
    							<form>
    								<div class="form-group position-relative mb-n1 mr-2 flex-shrink-0">
    									<input type="search" class="form-control form-control-sm rounded-pill" name="search_friend" placeholder="Search friend..." style="padding-left: 35px;">
    									<i class="fa fa-search position-absolute text-muted" style="top: 50%; left: 10px; transform: translateY(-50%);"></i>
    								</div>
    							</form>
                            {% endif %}
							<div class="flex-shrink-0 mt-1 mt-md-0">
								<a href="{% url 'user_search' %}" class="f-w6 small">Find Friends</a>
							</div>
						</div>
					</div>
                    {% if friends %}

                        <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); grid-gap: 20px;" class="mt-3">
                            {% for friend in friends %}
                                <div class="card d-flex flex-column align-items-center p-2">
                                    <div class="rounded-circle position-relative" style="width: 70px; height: 70px;">
                                        <img src="{{ friend.userprofile.get_profileimage }}">
                                        <a href="{% url 'profile_post' friend.pk %}" class="stretched-link"></a>
                                    </div>
                                    <a href="{% url 'profile_post' friend.pk %}">
                                        <h6 class="text-dark hover-blue">{{ friend.first_name }} {{ friend.last_name }}</h6>
                                    </a>
                                    <span class="small text-muted mb-2">16 Mutual Friends</span>
                                    <div>
                                        <span>
                                            <a href="#" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Send Message">
                                                <i class="fa fa-comment-alt"></i>
                                            </a>
                                        </span>
                                        <span data-toggle="modal" data-target="#remove-user-{{ friend.pk }}-modal">
                                            <button class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Remove Friend">
                                                <i class="fa fa-user-minus"></i>
                                            </button>
                                        </span>

                                        <!-- Remove Friend Modal -->

                                        <div class="modal fade" id="remove-user-{{ friend.pk }}-modal" tabindex="-1" role="dialog" aria-labelledby="remove-user-{{ friend.pk }}-modal-title" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="remove-user-{{ friend.pk }}-modal-title">Remove Friend</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                </div>
                                                <div class="modal-body">
                                                <p>Are you sure you want to remove "{{ friend.first_name }} {{ friend.last_name }}" as your friend?</p>
                                                </div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                <a href="{% url 'remove_friend' friend.pk %}" class="btn btn-danger">Yes, Remove</a>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                            {% endfor %}
                        </div>

                    {% else %}

                        <div class="p-3 mt-3 bg-white">
                            <h4 class="text-muted text-center">
                                No Friends
                                {% if request.GET.search_friend %}
                                    Named "{{ request.GET.search_friend }}"
                                {% endif %}
                            </h4>
                        </div>

                    {% endif %}
				</div>
			</div>
		</div>
    </div>

{% endblock content %}

accounts/templates/accounts/friend_request_list.html
{% extends 'base.html' %}

{% block title %}Friend Request List{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="card p-3 mt-3">
                    <h4 class="mb-4">Friend Request</h4>
                    <div class="d-flex flex-wrap">
                        {% for fr_user in friend_request_from_users %}
                            <div class="card mx-2 pb-2 shadow" style="width: 250px;">
                                <div class="rounded" style="height: 200px;">
                                    <img src="{{ fr_user.userprofile.get_profileimage }}" alt="">
                                </div>
                                <div class="mt-2 px-2 text-center">
                                    <h5 class="font-weight-lighter">{{ fr_user.first_name }} {{ fr_user.last_name }}</h5>
                                    <span></span>
                                </div>
                                <div class="mt-3 px-2">
                                    <div>
                                        <form action="{% url 'accept_friend_request' fr_user.pk %}" method="post" class="w-100">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm btn-outline-primary w-100">Accept Request</button>
                                        </form>
                                    </div>
                                    <div class="mt-2">
                                        <form action="{% url 'delete_friend_request' request.user.pk fr_user.pk %}" method="post" class="w-100">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm btn-outline-danger w-100">Delete Request</button>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        {% empty %}

                            <h4 class="mx-auto text-muted">No Friend Request</h4>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

accounts/templates/accounts/search_nav.html
<div>
    <h4 class="font-weight-bold">Search</h4>
    <div>
        <form>
            <div class="form-group">
                <input type="search" name="query" class="form-control" placeholder="Search Website">
            </div>
        </form>
    </div>
    <ul class="nav justify-content-around">
        <li class="nav-item">
            <a href="{% url 'user_search' %}{% if request.GET.query %}?query={{ request.GET.query }}{% endif %}" class="nav-link nav-item-line {% if 'user-search' in request.path %}active{% endif %} text-muted font-weight-bold profile__profile-nav-link" style="font-size: 17px;">Users</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'group_search' %}{% if request.GET.query %}?query={{ request.GET.query }}{% endif %}" class="nav-link nav-item-line text-muted font-weight-bold profile__profile-nav-link {% if 'group-search' in request.path %}active{% endif %}" style="font-size: 17px;">Groups</a>
        </li>
    </ul>
</div>

accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Settings{% endblock title %}

{% block content %}

	<div class="container mt-3">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card p-3">
					<h4>Account Settings</h4>
					<div class="mt-2">
						<form method="post">
							{% csrf_token %}
							{% if user_form.non_field_errors or profile.non_field_errors %}
								<div class="p-3 d-flex flex-column text-danger bg-t-red">
									{% for error in user_form.non_field_errors %}
										<span>{{ error }}</span>
									{% endfor %}
									{% for error in profile_form.non_field_errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% endif %}
							<div class="form-row">
								<div class="col-md-4 form-group">
									<label>First name</label>
									<input type="text" name="first_name" class="form-control {% if user_form.first_name.errors %}is-invalid{% endif %}" value="{% if user_form.first_name.value %}{{ user_form.first_name.value }}{% endif %}" id="id_first_name" aria-describedby="id_first_name_feedback">
									{% if user_form.first_name.errors %}
										<div class="invalid-feedback" id="id_first_name_feedback d-flex flex-column">
											{% for error in user_form.first_name.errors %}
												<span>{{ error }}</span>
											{% endfor %}
										</div>
									{% endif %}
								</div>
								<div class="col-md-4 form-group">
									<label>Last name</label>
									<input type="text" name="last_name" class="form-control {% if user_form.last_name.errors %}is-invalid{% endif %}" value="{% if user_form.last_name.value %}{{ user_form.last_name.value }}{% endif %}" id="id_last_name" aria-describedby="id_last_name_feedback">
									{% if user_form.last_name.errors %}
										<div class="invalid-feedback" id="id_last_name_feedback d-flex flex-column">
											{% for error in user_form.last_name.errors %}
												<span>{{ error }}</span>
											{% endfor %}
										</div>
									{% endif %}
								</div>
								<div class="col-md-4 form-group">
									<label>Other name</label>
									<input type="text" name="other_name" class="form-control {% if profile_form.other_name.errors %}is-invalid{% endif %}"  value="{% if profile_form.other_name.value %}{{ profile_form.other_name.value }}{% endif %}" id="id_other_name" aria-describedby="id_other_name_feedback">
									{% if profile_form.other_name.errors %}
										<div class="invalid-feedback" id="id_other_name_feedback d-flex flex-column">
											{% for error in profile_form.other_name.errors %}
												<span>{{ error }}</span>
											{% endfor %}
										</div>
									{% endif %}
								</div>
							</div>
							<div class="form-group">
								<label>Username</label>
								<input type="text" name="username" class="form-control {% if user_form.username.errors %}is-invalid{% endif %}" value="{% if user_form.username.value %}{{ user_form.username.value }}{% endif %}" id="id_username" aria-describedby="id_username_feedback" required>
								{% if user_form.username.errors %}
									<div class="invalid-feedback" id="id_username_feedback d-flex flex-column">
										{% for error in user_form.username.errors %}
											<span>{{ error }}</span>
										{% endfor %}
									</div>
								{% endif %}
							</div>
							<div class="form-row">
								<div class="col-md-6 form-group">
									<label>Phone Number</label>
									<input type="text" name="phone" class="form-control {% if profile_form.phone.errors %}is-invalid{% endif %}"  value="{% if profile_form.phone.value %}{{ profile_form.phone.value }}{% endif %}" id="id_phone" aria-describedby="id_phone_feedback">
									{% if profile_form.phone.errors %}
										<div class="invalid-feedback" id="id_phone_feedback d-flex flex-column">
											{% for error in profile_form.phone.errors %}
												<span>{{ error }}</span>
											{% endfor %}
										</div>
									{% endif %}
								</div>
								<div class="col-md-6 form-group">
									<label>Email</label>
									<input type="email" name="email" class="form-control {% if user_form.email.errors %}is-invalid{% endif %}" value="{% if user_form.email.value %}{{ user_form.email.value }}{% endif %}" id="id_email" aria-describedby="id_email_feedback">
									{% if user_form.email.errors %}
										<div class="invalid-feedback" id="id_email_feedback d-flex flex-column">
											{% for error in user_form.email.errors %}
												<span>{{ error }}</span>
											{% endfor %}
										</div>
									{% endif %}
								</div>
							</div>
							<button type="submit" name="user-profile-form" class="btn btn-primary d-block ml-auto">Save changes</button>
						</form>
					</div>
				</div>
				<div class="card p-3 mt-3">
					<h4>Change Password</h4>
					<div>
						<form method="post">
							{% csrf_token %}
							{{ password_form | crispy }}
							<button type="submit" name="password-form" class="btn btn-primary d-block ml-auto">Update Password</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}