chats/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.thread_view, name='threads'),
	path('<int:user_pk>/', views.thread_chat_view, name='thread_chat'),
	path('chat/<int:thread_pk>/create', views.chat_create_view, name='chat_create'),
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import user_signup_view
from posts.views import home_page_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', user_signup_view, name='signup'),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.account.urls')),
    path('', home_page_view, name='home'),  # root URL maps to HomePageView
    path('groups/', include('groups.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.models import User


# User = settings.AUTH_USER_MODEL

# Create your models here.

class ThreadManager(models.Manager):
	def get_or_new(self, user_pk, other_user_pk):
		if user_pk == other_user_pk:
			return None, False
		q1 = Q(first_id=user_pk) & Q(second_id=other_user_pk)
		q2 = Q(first_id=other_user_pk) & Q(second_id=user_pk)
		q = self.get_queryset().filter(q1 | q2)

		if q.count() == 1:
			return q.first(), False
		elif q.count() > 1:
			return q.order_by('created').first(), False
		elif not q.exists():
			user = User.objects.get(pk=user_pk)
			other_user = User.objects.get(pk=other_user_pk)
			obj = self.model(first=user, second=other_user)
			obj.save()
			return obj, True
		return None, False

	def get_thread_users(self, user_pk):
		qs = super().get_queryset().filter(
			Q(first_id=user_pk) | Q(second_id=user_pk)
		).order_by('-updated')
		user = User.objects.get(pk=user_pk)
		thread_users = [t.second if t.first.pk == user_pk else t.first for t in qs]
		for f in user.userprofile.friends.all():
			if f not in thread_users and f.pk != user_pk:
				thread_users.append(f)
		return thread_users

	def total_unseen_chat_count(self, user_pk):
		qs = super().get_queryset().filter(
			Q(first_id=user_pk) | Q(second_id=user_pk)
		)
		return sum([q.unseen_chat_count(user_pk) for q in qs])


class Thread(models.Model):
	first = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	second = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(default=timezone.now)

	objects = ThreadManager()

	def get_chat_data(self):
		chat_messages = list(self.chatmessage_set.all())
		chat_image_frames = list(self.chatimageframe_set.all())
		chat_data = [*chat_messages, *chat_image_frames]
		return sorted(chat_data, key=lambda x: x.created)

	def unseen_chat_count(self, user_pk):
		count = 0
		for chat_data in self.get_chat_data():
			if not chat_data.seen and chat_data.user.pk != user_pk:
				count += 1
		return count

	def seen_chat_message(self, user_pk):
		for chat_data in self.get_chat_data():
			if not chat_data.seen and chat_data.user.pk != user_pk:
				chat_data.seen = True
				chat_data.save()

	class Meta:
		ordering = ['-updated',]


class ChatMessage(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
	message = models.TextField()
	seen = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def save(self, *args, **kwargs):
		if self.pk:
			self.thread.updated = timezone.now()
			self.thread.save()
		return super(ChatMessage, self).save(*args, **kwargs)

class ChatImageFrame(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
	seen = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def save(self, *args, **kwargs):
		if self.pk:
			self.thread.updated = timezone.now()
			self.thread.save()
		return super(ChatImageFrame, self).save(*args, **kwargs)

class ChatImage(models.Model):
	frame = models.ForeignKey(ChatImageFrame, on_delete=models.Model)
	image = models.ImageField(upload_to='chat_images/%Y-%m-%d')
	created = models.DateTimeField(auto_now_add=True)

chats/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from chats.models import Thread
from django.contrib.auth.models import User
from django.http import JsonResponse
from posts.decorators import AjaxRequiredOnlyMixin
from chats.models import Thread, ChatImageFrame, ChatImage, ChatMessage
from chats.utils import get_thread_chat_data

# Create your views here.

class ThreadView(LoginRequiredMixin, TemplateView):
	template_name = 'chats/thread.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['page'] = 'thread'
		return context

thread_view = ThreadView.as_view()

class ThreadChatView(LoginRequiredMixin, TemplateView):
	template_name = 'chats/thread_chat.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		user_pk = kwargs['user_pk']
		thread, created = Thread.objects.get_or_new(user_pk=self.request.user.pk, other_user_pk=user_pk)
		thread.seen_chat_message(self.request.user.pk)
		context['thread'] = thread
		context['chat_user'] = User.objects.get(pk=user_pk)
		context['thread_data'] = thread.get_chat_data()
		return context 

thread_chat_view = ThreadChatView.as_view()

class ChatCreateView(AjaxRequiredOnlyMixin ,View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({'status': 'not logged in'})
		response = {'status': 'success'}
		message = request.POST.get('message')
		images = request.FILES.getlist('chat-image')
		thread = Thread.objects.get(pk=kwargs['thread_pk'])
		if message:
			chat_message = ChatMessage.objects.create(user=request.user, thread=thread, message=message)
			response['chat_message_pk'] = chat_message.pk
		if images:
			image_frame = ChatImageFrame.objects.create(user=request.user, thread=thread)
			for image in images:
				ChatImage.objects.create(frame=image_frame, image=image)
			response['image_frame_pk'] = image_frame.pk

		return JsonResponse(response)

chat_create_view = ChatCreateView.as_view()

groups/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.models import User
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    DetailView,
    View
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from groups.models import CustomGroup
from groups.forms import GroupCreateForm, GroupProfileImageForm
from groups.utils import get_all_group_photos, get_all_group_videos
from accounts.utils import filter_user_queryset

# Create your views here.

class GroupCreateView(LoginRequiredMixin, CreateView):
    model = CustomGroup
    form_class = GroupCreateForm
    template_name = 'groups/group_create.html'

    def form_valid(self, form):
        form = form.save()
        form.owner = self.request.user
        form.members.add(self.request.user)
        form.admin_members.add(self.request.user)
        form.save()
        return redirect(form.get_absolute_url())

group_create_view = GroupCreateView.as_view()

class GroupListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        filter_str = self.kwargs.get('group')
        url_path = self.request.path
        query = self.request.GET.get('query', '')
        print(query)
        if filter_str == 'my-groups':
            if 'search' in url_path:
                queryset = self.request.user.group.all().filter(name__icontains=query)
            else:
                queryset = self.request.user.group.all()
        elif filter_str == 'all-groups':
            if 'search' in url_path:
                queryset = CustomGroup.objects.all().filter(name__icontains=query)
            else:
                queryset = CustomGroup.objects.all()
        print(self.request.path)
        return queryset

group_list_view = GroupListView.as_view()

class GroupDetailView(LoginRequiredMixin, DetailView):
    model = CustomGroup
    context_object_name = 'group'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['posts'] = self.object.post_set.all().order_by('-created')
        return context
    
group_detail_view = GroupDetailView.as_view()

group_about_view = GroupDetailView.as_view(template_name = 'groups/group_about.html')

class GroupMembersListView(LoginRequiredMixin, DetailView):
    model = CustomGroup
    context_object_name = 'group'
    template_name = 'groups/group_members.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query = self.request.GET.get('search_member')
        if query:
            group_members = filter_user_queryset(self.object.members.all(), query)
        else:
            group_members = self.object.members.all().difference(
                self.object.admin_members.all(),
            )
        context['group_members'] = group_members
        return context 

group_members_list_view = GroupMembersListView.as_view()

class JoinGroupView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        group = CustomGroup.objects.get(pk=kwargs['group_pk'])
        user = User.objects.get(pk=kwargs['user_pk'])
        if user in group.members.all():
            group.members.remove(user)
            group.admin_members.remove(user)
        else:
            group.members.add(user)
        group.save()
        return redirect(request.META.get('HTTP_REFERER'))

join_group_view = JoinGroupView.as_view()

class GroupPhotosView(LoginRequiredMixin, TemplateView):
    template_name = 'groups/group_photos.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['photos'] = get_all_group_photos(kwargs['group_pk'])
        context['group'] = CustomGroup.objects.get(pk=kwargs['group_pk'])
        return context 

group_photos_view = GroupPhotosView.as_view()

class GroupVideosView(LoginRequiredMixin, TemplateView):
    template_name = 'groups/group_videos.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['videos'] = get_all_group_videos(kwargs['group_pk'])
        context['group'] = CustomGroup.objects.get(pk=kwargs['group_pk'])
        return context

group_videos_view = GroupVideosView.as_view()

class GroupSettingsView(UserPassesTestMixin, LoginRequiredMixin, TemplateView):
    template_name = 'groups/group_settings.html'

    def dispatch(self, request, *args, **kwargs):
        self.group = CustomGroup.objects.get(pk=kwargs['group_pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['group'] = self.group
        context['image_form'] = GroupProfileImageForm()
        context['group_form'] = GroupCreateForm(instance=self.group)
        return context

    def post(self, request, *args, **kwargs):
        image_form = GroupProfileImageForm(request.POST, request.FILES)
        group_form = GroupCreateForm(request.POST, instance=self.group)

        if image_form.is_valid() and group_form.is_valid():
            group_form.save()
            if request.FILES.get('image'):
                image_form = image_form.save(commit=False)
                image_form.group = self.group
                image_form.save()
            messages.success(request, 'Group Update Was Successful')
            return redirect(request.META.get('HTTP_REFERER'))
        return self.render_to_response({'image_form': image_form, 'group_form': group_form})

    def test_func(self):
        return self.request.user in self.group.admin_members.all()

group_settings_view = GroupSettingsView.as_view()

class GroupSearchView(LoginRequiredMixin, ListView):
    template_name = 'groups/group_search.html'

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        queryset = CustomGroup.objects.filter(name__icontains=query)
        return queryset

group_search_view = GroupSearchView.as_view()

chats/templates/chats/mobile_threadlist.html
<div class="position-fixed d-flex flex-column bg-white w-75 chat-left-mobile" style="z-index: 2000; top: 68px; left: -75%; height: calc(100vh - 68px)">
	<div class="px-3 pt-3 pb-2 d-flex justify-content-end">
		<i class="fa fa-times close-chat-left c-pointer" style="font-size: 25px;"></i>
	</div>
	<hr class="w-100">
	<div class="mx-3 mt-2">
		<form>
			<div class="form-group position-relative">
				<input type="text" name="search-chat" class="form-control text-muted" placeholder="Search for chats..." style="padding-right: 35px;">
				<button type="submit" class="bg-transparent position-absolute border-0" style="right: 10px; top: 50%; transform: translateY(-50%); cursor: pointer;">
					<i class="fa fa-search text-muted"></i>
				</button>
			</div>
		</form>
	</div>
	<div class="flex-grow-1 chat-list" style="overflow-y: auto;">
		{% for user in thread_users %}
			<div class="rounded py-2 px-3 my-2 d-flex align-items-center position-relative {% if user == chat_user %}current-chat{% endif %}">
				<div class="rounded-circle border border-primary position-relative" style="width: 50px; height: 50px; border-width: 2px !important; padding: 2px;">
					<img src="{{ user.userprofile.get_profileimage }}" class="rounded-circle">
					<span class="bg-white position-absolute rounded-circle d-flex justify-content-center align-items-center" style="width: 15px; height: 15px; right: -5px; top: 0;">
						<span class="bg-success rounded-circle" style="width: 60%; height: 60%;"></span>
					</span>
				</div>
				<div class="d-flex flex-column ml-2">
					<span class="font-weight-bold">{{ user.userprofile.full_name }}</span>
					<span class="small text-muted">Frances sent a photo.</span>
				</div>
				<a href="{% url 'thread_chat' user.pk %}" class="stretched-link"></a>
			</div>
		{% endfor %}
	</div>
</div>

chats/templates/chats/thread.html
{% extends 'base.html' %}
{% load chats_tags %}
{% load static %}

{% block title %}Chats{% endblock title %}

{% block content %}

	<div style="height: calc(100vh - 68px);">
	    <div class="d-flex flex-column justify-content-center align-items-center h-100 chat-container">
	        
	        <div class="d-flex flex-column flex-lg-row my-3 h-100 w-100">
	            {% thread_list %}

	            <div class="rounded border bg-white px-4 py-3 d-none d-lg-flex justify-content-center align-items-center" style="height: 100%; width: 75%;">
	            	<div style="width: 400px;">
	            		<img src="{% static 'images/chat.png' %}">
	            	</div>
	            </div>
	        </div>
	    </div>
    </div>

{% endblock content %}

chats/templates/chats/thread_chat.html
{% extends 'base.html' %}
{% load chats_tags %}
{% load static %}

{% block title %}Chats{% endblock title %}

{% block content %}

	<div style="height: calc(100vh - 68px);">
	    <div class="d-flex flex-column justify-content-center align-items-center chat-container h-100">
	        
	        <div class="d-flex flex-column flex-lg-row h-100 w-100">

	        	{% mobile_thread_list %}

	        	<!-- Chat Overlay (Mobile) -->

	        	<div class="position-fixed w-100 h-100 chat-overlay-mobile" style="top: 0; left: 0; z-index: 3; background: rgba(0, 0, 0, 0.5); visibility: hidden; opacity: 0;"></div>

	            {% thread_list %}

	            <div class="rounded border bg-white px-4 py-3 d-flex flex-column flex-grow-1 flex-lg-grow-0 main-chat" style="height: 100%; width: 75%;">

	            	<!-- Main Chat Header -->

	            	<div class="d-flex justify-content-between align-items-center">
	            		<div class="d-flex align-items-center">
	            			<div class="rounded-circle" style="width: 50px; height: 50px;">
	            				<img src="{{ chat_user.userprofile.get_profileimage }}" class="rounded-circle">
	            			</div>
	            			<div class="d-flex flex-column ml-2">
	            				<a href="{% url 'profile_post' chat_user.pk %}" class="font-weight-bold text-dark">{{ chat_user.userprofile.full_name }}</a>
	            			</div>
	            		</div>
	            	</div>

	            	<hr class="my-3 w-100">

	            	<!-- Messages -->

	            	<div class="flex-grow-1 chat-list" style="overflow-y: auto;">
	            		<div class="chat-data">
	            			{% for data in thread_data %}
		            			{% if data.user == request.user %}
		            				{% if data.message %}

			            				<div class="d-flex justify-content-end my-3">
			            					<div class="d-flex flex-column align-items-end">
			            						<span class="rounded bg-primary text-white mb-1 py-1 px-2">{{ data.message }}</span>
			            						<span class="text-muted small">{{ data.created | date:'d/m/y h:i A' }}</span>
			            					</div>
			            				</div>

		            				{% else %}

			            				<div class="d-flex justify-content-end my-3">
			            					<div class="d-flex flex-column align-items-end">
			            						{% for image in data.chatimage_set.all %}
				            						<div class="mb-1" style="width: 200px">
				            							<img src="{{ image.image.url }}" style="height: auto;">
				            						</div>
			            						{% endfor %}
			            						<span class="text-muted small">{{ data.created | date:'d/m/y h:i A' }}</span>
			            					</div>
			            				</div>

		            				{% endif %}
		            			{% else %}
			            			{% if data.message %}

				            			<div class="d-flex my-3">
				            				<div class="rounded-circle mr-1 flex-shrink-0" style="width: 30px; height: 30px;">
				            					<img src="{{ chat_user.userprofile.get_profileimage }}" class="rounded-circle">
				            				</div>
				            				<div class="d-flex flex-column ml-2">
				            					<span class="rounded background-llgrey mb-1 py-1 px-2">{{ data.message }}</span>
				            					<span class="text-muted small">{{ data.created | date:'d/m/y h:i A' }}</span>
				            				</div>
				            			</div>

				            		{% else %}

				            			<div class="d-flex my-3">
				            				<div class="rounded-circle mr-1 flex-shrink-0" style="width: 30px; height: 30px;">
				            					<img src="{{ chat_user.userprofile.get_profileimage }}" class="rounded-circle">
				            				</div>
			            					<div class="d-flex flex-column">
			            						{% for image in data.chatimage_set.all %}
				            						<div class="mb-1" style="width: 200px">
				            							<img src="{{ image.image.url }}" style="height: auto;">
				            						</div>
			            						{% endfor %}
			            						<span class="text-muted small">{{ data.created | date:'d/m/y h:i A' }}</span>
			            					</div>
			            				</div>

			            			{% endif %}
		            			{% endif %}
	            			{% endfor %}
	            		</div>
	            	</div>

	            	<hr class="my-3 w-100">

	            	<!-- Main Chat Send Chat Input -->

	            	<div>
	            		<div class="d-flex uploaded-img-container flex-wrap align-items-center"></div>
	            		<form class="form-inline chat-form justify-content-end align-items-center flex-nowrap chat-form" method="post" action="{% url 'chat_create' thread.pk %}" enctype="multipart/form-data">
	            			{% csrf_token %}
	            			<div class="form-group flex-grow-1 mb-2 mb-md-0">
	            				<input type="text" name="message" class="form-control w-100 chat-message" placeholder="Type a message">
	            			</div>
	            			<div class="form-group ml-2 mb-0">
	            				<label class="btn btn-sm background-lgrey py-2">
	            					<input type="file" name="chat-image" class="d-none post-create-img-input chat-image" multiple="multiple">
	            					<i class="fa fa-images"></i>
	            				</label>
	            			</div>
	            			<button type="submit" class="btn btn-sm btn-primary ml-2 align-self-start align-self-md-stretch py-2 py-md-0" style="padding: 0.275rem 0.75rem;">
	            				<i class="far fa-paper-plane"></i>
	            			</button>
	            		</form>
	            	</div>
	            </div>
	        </div>
	    </div>
	</div>
{% endblock content %}

{% block js %}
	<script src="{% static 'js/chat.js' %}"></script>
	<script src="{% static 'js/media-uploader.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js" integrity="sha512-SxQulwFs2B38bmUJtBSo9tD07MDrtCbY8me3AOZ14tRknCPTeMDLvCQV4ekhs8R0o9QPnW5HQanKfveexVcwLA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script>
		const chatForm = document.querySelector('.chat-form');
		const chatMessage = document.querySelector('.chat-message');
		const chatImage = document.querySelector('.chat-image');
		const chatData = document.querySelector('.chat-data');
		const formData = new FormData();

		async function submitFormData(formData) {
			const url = `{% url 'chat_create' thread.pk %}`
			try {
				const response = await fetch(url, {
					method: 'POST',
					headers: {
						'Accept': 'application/json',
				        "X-Requested-With": "XMLHttpRequest",
				        "HTTP_X_REQUESTED_WITH": "XMLHttpRequest",
						'X-CSRFToken': '{{csrf_token}}',
					},
					body: formData,
				});
				const result = await response.json();
				return result;
			} catch (error) {
				console.log('Error', error);
			};
		};

		chatForm.addEventListener('submit', function(e) {
			e.preventDefault();
			formData.append(chatMessage.getAttribute('name'), chatMessage.value);
			const photos = chatImage.files;
			for (let i = 0; i < photos.length; i++) {
				formData.append('chat-image', photos[i]);
			};
			submitFormData(formData).then(response => {
				if (response.status == 'success') {
					const clearImgsBtn = document.querySelector('.clear-imgs-btn');
					if (clearImgsBtn) clearImgsBtn.click();
					chatMessage.value = '';
					sendChatData(response);
				};
			});
		});

		let loc = window.location;
		let wsProtocol = loc.protocol == 'http:' ? 'ws://' : 'wss://';
		const path = wsProtocol + loc.host + '/ws' + loc.pathname;
		const chatSocket = new ReconnectingWebSocket(path);

		function sendChatData(response) {
			chatSocket.send(JSON.stringify(response));
		};

		chatSocket.onmessage = function (e) {
			updateChat(JSON.parse(e.data).data);
		};


		function updateChat(data) {
			new_chat = ''
			if (data.user == '{{ request.user.username }}') {
				if (data.chat_message) {
					new_chat += `
						<div class="d-flex justify-content-end my-3">
							<div class="d-flex flex-column align-items-end">
								<span class="rounded bg-primary text-white mb-1 py-1 px-2">${data.chat_message}</span>
								<span class="text-muted small">${data.date}</span>
							</div>
						</div>
					`
				}
				if (data.chat_images) {
					new_chat += `
						<div class="d-flex justify-content-end my-3">
			            	<div class="d-flex flex-column align-items-end">
					`
					for (let img of data.chat_images) {
						new_chat += `
							<div class="mb-1" style="width: 200px">
								<img src="${img}" style="height: auto;">
							</div>
						`
					}
					new_chat += `
								<span class="text-muted small">${data.date}</span>
							</div>
						</div>
					`
				}
			} else {
				if (data.chat_message) {
					new_chat += `
						<div class="d-flex my-3">
							<div class="rounded-circle mr-1 flex-shrink-0" style="width: 30px; height: 30px;">
								<img src="{{ chat_user.userprofile.get_profileimage }}" class="rounded-circle">
							</div>
							<div class="d-flex flex-column ml-2">
								<span class="rounded background-llgrey mb-1 py-1 px-2">${data.chat_message}</span>
								<span class="text-muted small">${data.date}</span>
							</div>
						</div>
					`
				}
				if (data.chat_images) {
					new_chat += `
            			<div class="d-flex my-3">
            				<div class="rounded-circle mr-1 flex-shrink-0" style="width: 30px; height: 30px;">
            					<img src="{{ chat_user.userprofile.get_profileimage }}" class="rounded-circle">
            				</div>
        					<div class="d-flex flex-column">
					`
					for (let img of data.chat_images) {
						new_chat += `
							<div class="mb-1" style="width: 200px">
								<img src="${img}" style="height: auto;">
							</div>
						`
					}
					new_chat += `
								<span class="text-muted small">${data.date}</span>
							</div>
						</div>
					`
				}
			}
			chatData.innerHTML += new_chat;
		}
	</script>
{% endblock js %}

chats/templates/chats/threadlist.html
{% load chats_tags %}
<div class="rounded border px-3 py-2 py-lg-3 bg-white {% if page != 'thread' %}d-none d-lg-flex{% else %}d-flex{% endif %} flex-column chat-left" style="height: 100%; width: 25%;">
    <div class="d-flex justify-content-between">
        <div class="d-flex align-items-center">
            <h5 class="font-weight-bold" style="font-size: 22px;">Chats</h5>
            <span class="badge badge-success ml-1 font-weight-normal" style="font-size: 14px;">9</span>
        </div>
        <div class="bg-primary rounded chat-hamburger-menu d-none flex-column justify-content-center align-items-center" style="width: 35px; height: 30px; cursor: pointer;">
            <div class="rounded bg-white" style="width: 15px; height: 3px; margin: 1.5px 10px 1.5px 0;"></div>
            <div class="rounded bg-white" style="width: 15px; height: 3px; margin: 1.5px 0;"></div>
            <div class="rounded bg-white" style="width: 15px; height: 3px; margin: 1.5px -10px 1.5px 0;"></div>
        </div>
    </div>
    <div class="">
        <hr class="mx-n3">
        <div class="">
            <form>
                <div class="form-group position-relative">
                    <input type="text" name="search-chat" class="form-control text-muted" placeholder="Search for chats..." style="padding-right: 35px;">
                    <button type="submit" class="bg-transparent position-absolute border-0" style="right: 10px; top: 50%; transform: translateY(-50%); cursor: pointer;">
                        <i class="fa fa-search text-muted"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="flex-grow-1 chat-list " style="overflow-y: auto;">
        {% for user in thread_users %}

            <div class="rounded py-2 px-3 my-2 d-flex align-items-center position-relative {% if user == chat_user %}current-chat{% endif %}">
                <div class="rounded-circle border border-primary position-relative" style="width: 50px; height: 50px; border-width: 2px !important; padding: 2px;">
                    <img src="{{ user.userprofile.get_profileimage }}" class="rounded-circle">
                </div>
                <div class="d-flex flex-column ml-2">
                    <span class="font-weight-bold">{{ user.userprofile.full_name }}</span>
                </div>
                {% thread_unseen_chat_count request.user.pk user.pk as ucc %}
                {% if ucc %}
                    <span class="badge badge-pill badge-danger f-sm ml-auto">{{ ucc }}</span>
                {% endif %}
                <a href="{% url 'thread_chat' user.pk %}" class="stretched-link"></a>
            </div>

        {% endfor %}
    </div>
</div>