chats/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.thread_view, name='threads'),
	path('<int:user_pk>/', views.thread_chat_view, name='thread_chat'),
	path('chat/<int:thread_pk>/create', views.chat_create_view, name='chat_create'),
]

posts/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
	path('', views.home_page_view, name='home'),
	path('<int:post_pk>/', views.home_page_view, name='home'),
	path('group-post/<int:group_pk>/create/', views.home_page_view, name='create_group_post'),
	path('post/<int:pk>/', views.post_detail_view, name='post_detail'),
	path('post/<int:pk>/edit/', views.post_edit_view, name='post_edit'),
	path('image/<int:image_pk>/delete/', views.delete_postimage_view, name='delete_postimage'),
	path('post-image/<int:post_pk>/add/', views.add_postimage_view, name='add_postimage'),
	path('post-image/<int:post_pk>/delete-all/', views.delete_all_postimage_view, name='delete_all_postimage'),
	path('post-video/<int:post_pk>/', views.post_video_view, name='post_video'),
	path('post/<int:post_pk>/delete/', views.post_delete_view, name='post_delete'),
	path('post/<int:post_pk>/like/', views.post_likes_view, name='post_like'),
	path('comment/<int:post_pk>/create/', views.comment_create_view, name='comment_create'),
	path('reply/<int:comment_pk>/create/', views.reply_create_view, name='reply_create'),
	path('comment/<int:comment_pk>/edit/', views.comment_edit_view, name='comment_edit'),
	path('reply/<int:reply_pk>/edit/', views.reply_edit_view, name='reply_edit'),
	path('comment/<int:comment_pk>/delete/', views.comment_delete_view, name='comment_delete'),
	path('reply/<int:reply_pk>/delete/', views.reply_delete_view, name='reply_delete'),
	path('comment/<int:comment_pk>/like/', views.comment_likes_view, name='comment_like'),
	path('reply/<int:reply_pk>/like/', views.reply_likes_view, name='reply_like'),
	# path('shared-post/<int:post_pk>/create/', views.shared_post_create_view, name='shared_post_create'),
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import user_signup_view
from posts.views import home_page_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', user_signup_view, name='signup'),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.account.urls')),
    path('', home_page_view, name='home'),  # root URL maps to HomePageView
    path('groups/', include('groups.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from groups.models import CustomGroup
from cloudinary_storage.storage import VideoMediaCloudinaryStorage
# from cloudinary_storage.validators import validate_video


User = settings.AUTH_USER_MODEL

# Create your models here.

class Post(models.Model):
	STATUSES = (
		('public', 'PUBLIC'),
		('friends', 'FRIENDS'),
		('only me', 'ONLY ME'),
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	shared_post = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
	group = models.ForeignKey(CustomGroup, on_delete=models.SET_NULL, null=True, blank=True)
	content = models.TextField()
	video = models.FileField(
		upload_to='post_video/%Y-%m-%d/',
		storage=VideoMediaCloudinaryStorage(),
		validators=[FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'flv', 'mov', 'ogv' ,'3gp' ,'3g2' ,'wmv' , 'mpeg' ,'flv' ,'mkv' ,'avi'])],
		null=True,
		blank=True
	)
	likes = models.ManyToManyField(User, related_name='+')
	visibility = models.CharField(max_length=100, choices=STATUSES)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f'{self.pk} -- {self.user}'

	def get_absolute_url(self):
		return reverse('post_detail', kwargs={'pk': self.pk})

	@property
	def comment_count(self):
		reply_list = [comment.reply_set.all().count() for comment in self.comment_set.all()]
		return sum(reply_list) + len(reply_list)

class PostImage(models.Model):
	image = models.ImageField(upload_to='post_images/%Y-%m-%d/')
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.post.pk} -- {self.post.user}'

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	comment = models.TextField()
	likes = models.ManyToManyField(User, related_name='+')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f'{self.user.username} comments on {self.post}'

	class Meta:
		ordering = ['-created',]

class Reply(models.Model):
	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	reply = models.TextField()
	likes = models.ManyToManyField(User, related_name='+')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f'{self.user.username} reply on {self.comment.user} comment on {self.comment.post.user} post'

	class Meta:
		ordering = ['-created',]

posts/forms.py
from django import forms
from posts.models import Post, PostImage, Comment, Reply


class PostCreateForm(forms.ModelForm):
	class Meta:
		model = Post 
		fields = ['content', 'video', 'visibility']

class PostEditForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['content',]

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment',]

class ReplyForm(forms.ModelForm):
	class Meta:
		model = Reply
		fields = ['reply',]

# class SharedPostForm(forms.ModelForm):
# 	class Meta:
# 		model = SharedPost
# 		fields = ['visibility',]

posts/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views.generic import TemplateView, DetailView, View, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms.models import model_to_dict
from django.http import JsonResponse
from posts.forms import PostCreateForm, PostEditForm, CommentForm, ReplyForm
from posts.models import PostImage, Post, Comment, Reply
from posts.utils import get_feeds_queryset
from posts.decorators import AjaxRequiredOnlyMixin
from groups.models import CustomGroup
import logging

logger = logging.getLogger(__name__)

class HomePageView(UserPassesTestMixin, LoginRequiredMixin, TemplateView):
    template_name = 'posts/home.html'
    group = None

    def dispatch(self, request, *args, **kwargs):
        group_pk = kwargs.get('group_pk')
        if group_pk:
            try:
                self.group = CustomGroup.objects.get(pk=group_pk)
            except CustomGroup.DoesNotExist:
                logger.error(f"Group with pk={group_pk} does not exist.")
                self.group = None
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        try:
            context['posts'] = get_feeds_queryset(self.request)
        except Exception as e:
            logger.error(f"Error getting feed posts: {e}")
            context['posts'] = []  # fallback to empty list
        context['page'] = 'home'
        return context

    def post(self, request, *args, **kwargs):
        post_form = PostCreateForm(request.POST, request.FILES)
        redirect_url = 'home'
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            if self.group:
                post.group = self.group
                post.visibility = 'public'
                redirect_url = self.group.get_absolute_url()
            try:
                post.shared_post = Post.objects.get(pk=kwargs.get('post_pk'))
            except (Post.DoesNotExist, TypeError):
                pass
            post.save()

            for image in request.FILES.getlist('images'):
                PostImage.objects.create(post=post, image=image)

            return redirect(redirect_url)

        return self.render_to_response({'post_form': post_form})

    def test_func(self):
        if self.group:
            return self.request.user in self.group.members.all()
        return True

home_page_view = HomePageView.as_view()

class PostDetailView(LoginRequiredMixin, DetailView):
	model = Post

post_detail_view = PostDetailView.as_view()

class PostEditView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
	model = Post
	fields = ['content', 'visibility']
	def test_func(self):
		return self.request.user == self.get_object().user

post_edit_view = PostEditView.as_view()

class DeletePostImageView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		PostImage.objects.get(pk=kwargs['image_pk']).delete()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == PostImage.objects.get(pk=self.kwargs['image_pk']).post.user

delete_postimage_view = DeletePostImageView.as_view()

class AddPostImageView(UserPassesTestMixin, LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		images = request.FILES.getlist('images')
		post = Post.objects.get(pk=kwargs['post_pk'])
		if images:
			for image in images:
				PostImage.objects.create(post=post, image=image)
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Post.objects.get(pk=self.kwargs['post_pk']).user

add_postimage_view = AddPostImageView.as_view()

class DeleteAllPostImageView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		Post.objects.get(pk=kwargs['post_pk']).postimage_set.all().delete()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Post.objects.get(pk=self.kwargs['post_pk']).user

delete_all_postimage_view = DeleteAllPostImageView.as_view()

class PostVideoView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		post = Post.objects.get(pk=kwargs['post_pk'])
		post.video = None
		post.save()
		return redirect(request.META.get('HTTP_REFERER'))
	def post(self, request, *args, **kwargs):
		video = request.FILES.get('video')
		post = Post.objects.get(pk=kwargs['post_pk'])

		if video:
			post.video = video
			post.save()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Post.objects.get(pk=self.kwargs['post_pk']).user

post_video_view = PostVideoView.as_view()

class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		Post.objects.get(pk=kwargs['post_pk']).delete()
		return redirect('home')

	def test_func(self):
		post = Post.objects.get(pk=self.kwargs['post_pk'])
		if post.group:
			return self.request.user == post.user or self.request.user in post.group.members.all()
		return self.request.user == post.user

post_delete_view = PostDeleteView.as_view()

class PostLikesView(AjaxRequiredOnlyMixin, View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({'status': 'not logged in'})
		post = Post.objects.get(pk=kwargs['post_pk'])
		if request.user in post.likes.all():
			post.likes.remove(request.user)
			action = 'unlike'
		else:
			post.likes.add(request.user)
			action = 'like'
		return JsonResponse({'status': 'ok', 'action': action, 'num_of_likes': post.likes.all().count()})

post_likes_view = PostLikesView.as_view()

class CommentCreateView(LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		post = Post.objects.get(pk=kwargs['post_pk'])
		comment_form = CommentForm(request.POST)
		if comment_form.is_valid():
			form = comment_form.save(commit=False)
			form.user = request.user
			form.post = post
			form.save()
		return redirect(request.META.get('HTTP_REFERER'))

comment_create_view = CommentCreateView.as_view()

class ReplyCreateView(LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		comment = Comment.objects.get(pk=kwargs['comment_pk'])
		reply_form = ReplyForm(request.POST)
		if reply_form.is_valid():
			form = reply_form.save(commit=False)
			form.comment = comment
			form.user = request.user
			form.save()
		return redirect(request.META.get('HTTP_REFERER'))

reply_create_view = ReplyCreateView.as_view()

class CommentEditView(UserPassesTestMixin, LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		comment = Comment.objects.get(pk=kwargs['comment_pk'])
		comment_form = CommentForm(request.POST, instance=comment)
		if comment_form.is_valid():
			comment_form.save()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Comment.objects.get(pk=self.kwargs['comment_pk']).user

comment_edit_view = CommentEditView.as_view()

class ReplyEditView(UserPassesTestMixin, LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		reply = Reply.objects.get(pk=kwargs['reply_pk'])
		reply_form = ReplyForm(request.POST, instance=reply)
		if reply_form.is_valid():
			reply_form.save()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Reply.objects.get(pk=self.kwargs['reply_pk']).user

reply_edit_view = ReplyEditView.as_view()

class CommentDeleteView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		Comment.objects.get(pk=kwargs['comment_pk']).delete()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Comment.objects.get(pk=self.kwargs['comment_pk']).user

comment_delete_view = CommentDeleteView.as_view()

class ReplyDeleteView(UserPassesTestMixin, LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		Reply.objects.get(pk=kwargs['reply_pk']).delete()
		return redirect(request.META.get('HTTP_REFERER'))

	def test_func(self):
		return self.request.user == Reply.objects.get(pk=self.kwargs['reply_pk']).user

reply_delete_view = ReplyDeleteView.as_view()

class CommentLikesView(AjaxRequiredOnlyMixin, View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({'status': 'not logged in'})
		comment = Comment.objects.get(pk=kwargs['comment_pk'])
		if request.user in comment.likes.all():
			comment.likes.remove(request.user)
			action = 'unlike'
		else:
			comment.likes.add(request.user)
			action = 'like'
		return JsonResponse({'status': 'ok', 'action': action, 'num_of_likes': comment.likes.all().count()})

comment_likes_view = CommentLikesView.as_view()

class ReplyLikesView(AjaxRequiredOnlyMixin, View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({'status': 'not logged in'})
		reply = Reply.objects.get(pk=kwargs['reply_pk'])
		if request.user in reply.likes.all():
			reply.likes.remove(request.user)
			action = 'unlike'
		else:
			reply.likes.add(request.user)
			action = 'like'
		return JsonResponse({'status': 'ok', 'action': action, 'num_of_likes': reply.likes.all().count()})

reply_likes_view = ReplyLikesView.as_view()

posts/templates/posts/home.html
{% extends 'base.html' %}
{% load posts_tags %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

	<div class="container">
		<div class="row py-3">
			{% include 'posts/left-section.html' %}
			<div class="col-lg-6">
				{% url 'home' as post_url %}
				{% include 'posts/post-create.html' with post_url=post_url %}

				{% include 'posts/post-feeds.html' %}
			</div>
			{% chats request.user.pk %}
		</div>
	</div>

{% endblock content %}

{% block js %}
	<script src="{% static 'js/media-uploader.js' %}"></script>
	{% include 'posts/post_like_script.html' %}
{% endblock js %}

posts/templates/posts/left-section.html
<div class="col-lg-3 d-none d-lg-block">
	<div class="bg-white p-3">
		<ul class="list-unstyled">
			<li class="mb-3">
				<a href="{% url 'home' %}" class="d-flex align-items-center text-dark left-nav-link">
					<div style="padding: 10px;" class="rounded-circle d-flex justify-content-center align-items-center bg-light">
						<i class="fa fa-list-alt"></i>
					</div>
					<span class="font-weight-bold ml-2">Feed</span>
				</a>
			</li>
			<li class="mb-3">
				<a href="{% url 'groups' 'all-groups' %}" class="d-flex align-items-center text-dark left-nav-link">
					<div style="padding: 10px;" class="rounded-circle d-flex justify-content-center align-items-center bg-light">
						<i class="fa fa-users"></i>
					</div>
					<span class="font-weight-bold ml-2">Groups</span>
				</a>
			</li>
			<li class="mb-3">
				<a href="#" class="d-flex align-items-center text-dark left-nav-link">
					<div style="padding: 10px;" class="rounded-circle d-flex justify-content-center align-items-center bg-light">
						<i class="fa fa-bell"></i>
					</div>
					<span class="font-weight-bold ml-2">Notifications</span>
				</a>
			</li>
			<li class="mb-3">
				<a href="{% url 'user_settings' %}" class="d-flex align-items-center text-dark left-nav-link">
					<div style="padding: 10px;" class="rounded-circle d-flex justify-content-center align-items-center bg-light">
						<i class="fa fa-gear"></i>
					</div>
					<span class="font-weight-bold ml-2">Settings</span>
				</a>
			</li>
		</ul>
	</div>
</div>

posts/templates/posts/post-create.html
<!-- Create Post Section -->

<div class="p-3 rounded bg-white">
	<form method="post" action="{{ post_url }}" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-group position-relative">
			<textarea class="form-control rounded pl-5 {% if post_form.content.errors %}is-invalid{% endif %}" id="id_content" aria-describedby="id_content_feedback" placeholder="What's on your mind?" rows="3" name="content"></textarea>
			<div class="position-absolute rounded-circle" style="top: 7px; left: 7px; width: 30px; height: 30px;">
				<img class="rounded-circle" style="width: 100%; height: 100%;" src="{{ request.user.userprofile.get_profileimage }}">
			</div>
			{% if post_form.content.errors %}
				<div class="invalid-feedback d-flex flex-column" id="id_content_feedback">
					{% for error in post_form.content.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% endif %}
		</div>
		<div class="d-flex flex-wrap justify-content-between">
			<div class="d-flex align-items-center">
				<div class="form-group">
					<label class="btn btn-sm btn-light position-relative" style="padding-left: 35px;">
						Images
						<input class="d-none post-create-img-input" type="file" name="images" multiple="multiple" accept="image/jpeg, image/png, image/jpg">
						<i class="fa fa-images position-absolute text-success" style="top: 50%; left: 8px; transform: translateY(-50%);"></i>
					</label>
				</div>
				<div class="form-group mx-3">
					<label class="btn btn-sm btn-light position-relative" style="padding-left: 35px;">
						Video
						<input class="d-none post-create-video-input" id="id_video" aria-describedby="id_video_feedback" type="file" name="video" accept="video/mp4, video/ogg, video/webm">
						<i class="fa fa-video position-absolute text-danger" style="top: 50%; left: 8px; transform: translateY(-50%);"></i>
					</label>
					{% if post_form.video.errors %}
						<div class="invalid-feedback d-flex flex-column" id="id_video_feedback">
							{% for error in post_form.video.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% endif %}
				</div>
			</div>
			<div class="d-flex">
				<div class="form-group {% if 'groups' in request.path %}d-none{% endif %}">
					<select class="form-control form-control-sm" name="visibility" style="width: 100px;">
						<option value="public">Public</option>
						<option value="friends">Friends</option>
						<option value="only me">Only Me</option>
					</select>
				</div>
				<div class="form-group ml-2">
					<button class="btn btn-sm btn-primary" type="submit">Post</button>
				</div>
			</div>
		</div>
		<div>
			<div class="d-flex uploaded-img-container flex-wrap align-items-center"></div>
		</div>
		<div class="d-flex align-items-center uploaded-video-container">
		</div>
	</form>
</div>

posts/templates/posts/post-share-modal.html
{% load posts_tags %}
<div class="modal fade" id="share-post-{{ post.pk }}-modal" tabindex="-1" role="dialog" aria-labelledby="share-post-{{ post.pk }}-modal-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="share-post-{{ post.pk }}-modal-title">Share Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'home' post.pk %}">
      	{% csrf_token %}
	    <div class="modal-body">
	    	<div>
		        <div>
		        	<div class="d-flex align-items-center">
						<div class="rounded-circle border border-primary flex-shrink-0" style="width: 50px; height: 50px; border-width: 2px !important; padding: 2px;">
							<img src="{{ request.user.userprofile.get_profileimage }}">
						</div>
						<div class="d-flex flex-column justify-content-center ml-2">
							<a href="{% url 'profile_post' post.user.pk %}" class="font-weight-bold text-dark">{{ request.user.first_name }} {{ request.user.last_name }}</a>
							<a href="{% url 'profile_post' post.user.pk %}" class="text-muted small">@{{ request.user.username }}</a>
						</div>
						<div style="width: 100px;" class="ml-auto">
							<div class="form-group">
								<select class="form-control" name="visibility">
									<option value="public">Public</option>
									<option value="friends">Friends</option>
									<option value="only me">Only Me</option>
								</select>
							</div>
						</div>
					</div>
					<div class="form-group mt-3">
						<textarea class="form-control" name="content" placeholder="What's on your mind?"></textarea>
					</div>
		        </div>
	        </div>
	        <div class="border border-primary rounded p-3">
	        	<div class="d-flex">
					<div class="rounded-circle border border-primary flex-shrink-0 mr-2" style="width: 50px; height: 50px; border-width: 2px !important; padding: 2px;">
						<img src="{{ post.user.userprofile.get_profileimage }}">
					</div>
					{% if post.group %}

						<div class="d-flex flex-column">
							<a href="{{ post.group.get_absolute_url }}">
								<span class="text-dark font-weight-bold">{{ post.group.name }}</span>
							</a>
							<div class="text-muted small d-flex align-items-center font-weight-bold">
								<a href="{% url 'profile_post' post.user.pk %}" class="text-muted">{{ post.user.userprofile.full_name }}</a>
								<i class="fa fa-circle mx-2" style="font-size: 5px;"></i>
								<span class="small">{{ post.created | timesince | truncatechars:5}}</span>
							</div>
						</div>

					{% else %}

						<div class="d-flex flex-column justify-content-center">
							<span class="d-flex align-items-center">
								<a href="{% url 'profile_post' post.user.pk %}" class="font-weight-bold text-dark">{{ post.user.userprofile.full_name }}</a>
								<span class="text-muted mx-1 d-flex align-items-center justify-content-center"><i class="fa fa-circle" style="font-size: 5px;"></i></span>
								<span class="text-muted small">{{ post.created | timesince | truncatechars:5 }}</span>
							</span>
							<a href="{% url 'profile_post' post.user.pk %}" class="text-muted small">@{{ post.user.username }}</a>
						</div>

					{% endif %}
				</div>
				<div class="mt-3 text-muted d-flex flex-column align-items-start mb-2">
					<span>{{ post.content | truncatewords:30 }}</span>
					<!-- <a href="{% url 'post_detail' post.pk %}">View Details</a> -->
				</div>

				{% if post.postimage_set.all %}
					<div class="mt-2 mb-3 post-img-{% if post.postimage_set.all.count > 3 %}3{% else %}{{ post.postimage_set.all.count }}{% endif %}" style="height: 280px;">
						{% post_imgs post as images %}
						{% for image in images %}
							<div class="rounded img-modal-trigger" style="cursor: pointer;" data-toggle="modal" data-target="#post{{ post.pk }}-modal" data-imgid="#modal-img-{{ image.pk }}">
								<img src="{{ image.image.url }}" class="rounded">
							</div>
						{% endfor %}
						<div class="modal fade" id="post{{ post.pk }}-modal">
							<div class="modal-dialog modal-dialog-centered">
								<div class="modal-content" style="height: 500px;">
									<div class="modal-body h-100">
										<div class="carousel slide h-100" id="post{{ post.pk }}-carousel" data-ride="carousel">
											<div class="carousel-inner h-100">
												{% for image in post.postimage_set.all %}
													<div class="carousel-item h-100" id="modal-img-{{ image.pk }}">
														<img src="{{ image.image.url }}" class="d-block w-100">
													</div>
												{% endfor %}
											</div>
											<button type="button" class="carousel-control-prev" data-slide="prev" data-target="#post{{ post.pk }}-carousel">
												<span class="carousel-control-prev-icon"></span>
												<span class="sr-only">Previous</span>
											</button>
											<button type="button" class="carousel-control-next" data-slide="next" data-target="#post{{ post.pk }}-carousel">
												<span class="carousel-control-next-icon"></span>
												<span class="sr-only">Next</span>
											</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				{% endif %}
				{% if post.video %}

					<div class="mt-4">
						<div class="section d-flex justify-content-center embed-responsive embed-responsive-16by9">
							<video class="embed-responsive-item" controls>
								<source src="{{ post.video.url }}#t=0.2" type="video/mp4">
							</video>
						</div>
					</div>

				{% endif %}
	        </div>
	    </div>
	    <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
	        <button type="submit" class="btn btn-primary">Share</button>
	    </div>
      </form>
    </div>
  </div>
</div>

posts/templates/posts/right-section.html
<div class="col-lg-3 d-none d-lg-block">
	<div class="p-3 bg-white">
		<h5 class="font-weight-bold">Messenger</h5>
		<ul class="list-unstyled mt-4">
			{% for user in user_threads %}
				<li class="mt-4">
					<a href="{% url 'thread_chat' user.pk %}" class="d-flex align-items-center">
						<div class="rounded-circle" style="width: 35px; height: 35px;">
							<img src="{{ user.userprofile.get_profileimage }}" class="rounded-circle">
						</div>
						<span class="ml-2 font-weight-bold text-dark">{{ user.userprofile.full_name }}</span>
					</a>
				</li>
			{% empty %}
				<h4 class="text-muted">No Chat Or Messages</h4>
			{% endfor %}
		</ul>
	</div>
</div>